# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-03 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainWheel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=200, verbose_name='首页轮播图片')),
                ('name', models.CharField(max_length=64, verbose_name='轮播标题')),
                ('trackid', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '主页轮播图',
                'db_table': 'axf_wheel',
            },
        ),
    ]
