# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-03 11:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_foodtype_goods_mainmustbuy_mainnav_mainshop_mainshow'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mainshow',
            table='axf_mainshow',
        ),
    ]
